"""
ClarificationEnv: the RL environment for the constrained clarification task.

One episode = one problem. The agent receives the degraded spec and either:
  [ASK]    followed by a clarifying question  → user simulator answers
  [ANSWER] followed by Python code             → code executor scores

Prompts are built using the model's chat template (e.g. Qwen's <|im_start|>
format) so that instruction-tuned models reliably follow instructions.
The environment is stateless across episodes; each episode is independent.
"""

import asyncio
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

from src.data.dataset import Problem
from src.environment.code_executor import CodeExecutor, extract_code, _extract_helper_context
from src.environment.user_simulator import UserSimulator


# ── Prompt templates ──────────────────────────────────────────────────────────

_SYSTEM_PROMPT = """\
You are a coding assistant. Given a coding task below, you must either:
  - Ask a clarifying question by responding with [ASK] followed by your question.
  - Write your Python solution by responding with [ANSWER] followed by the code.

Important rules:
  - Respond with ONLY one action per turn ([ASK] or [ANSWER]).
  - When you have enough information, write the code.
  - Do not explain your reasoning — just output the action directly."""


def _build_prompt(problem: Problem, conversation: List[Tuple[str, str]], tokenizer) -> str:
    """
    Build the full text prompt for the agent at the current turn,
    using the model's chat template for proper instruction following.

    Args:
        problem:      the current problem
        conversation: list of (question, answer) pairs from previous turns
        tokenizer:    HuggingFace tokenizer with a chat template

    Returns:
        Formatted prompt string (with chat template special tokens).
    """
    messages = [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {"role": "user", "content": f"Task:\n{problem.degraded_prompt}"},
    ]

    for question, answer in conversation:
        messages.append({"role": "assistant", "content": f"[ASK] {question}"})
        messages.append({"role": "user", "content": answer})

    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True,
    )


# ── State & step result ───────────────────────────────────────────────────────

@dataclass
class EnvState:
    problem: Problem
    conversation: List[Tuple[str, str]]   # (question, answer) pairs
    turn_count: int
    question_count: int                   # total atomic questions asked
    done: bool
    prompt: str                           # current full text prompt

    @property
    def is_truncated(self) -> bool:
        """True if the episode ended due to hitting max_turns, not [ANSWER]."""
        return self.done and not any(
            t[0].upper().startswith("[ANSWER]") for t in self.conversation
        )


@dataclass
class StepResult:
    next_state: EnvState
    reward: float       # pass@1 (non-zero only on [ANSWER] turns)
    cost_q: float       # number of atomic questions asked this turn
    cost_t: float       # always 1.0 (each turn costs one turn)
    done: bool
    info: dict          # extra info for logging


# ── Environment ───────────────────────────────────────────────────────────────

class ClarificationEnv:
    def __init__(self, cfg, tokenizer):
        self.cfg = cfg
        self.max_turns = cfg.environment.max_turns
        self.tokenizer = tokenizer
        self.simulator = UserSimulator(cfg)
        self.executor = CodeExecutor(cfg)
        self.efficiency_alpha = getattr(cfg.environment, "efficiency_alpha", 0.0)
        self.efficiency_beta = getattr(cfg.environment, "efficiency_beta", 0.0)
        self.question_budget = getattr(cfg.constraint, "d1", 1)

    def reset(self, problem: Problem) -> EnvState:
        """Start a new episode with the given problem."""
        prompt = _build_prompt(problem, conversation=[], tokenizer=self.tokenizer)
        return EnvState(
            problem=problem,
            conversation=[],
            turn_count=0,
            question_count=0,
            done=False,
            prompt=prompt,
        )

    async def step(self, state: EnvState, action_text: str) -> StepResult:
        """
        Take one environment step given the agent's raw output text.

        Args:
            state:       current EnvState
            action_text: raw text generated by the agent (e.g. "[ASK] What is X?")

        Returns:
            StepResult with (next_state, reward, cost_q, cost_t, done, info)
        """
        action_upper = action_text.strip().upper()
        turn_count = state.turn_count + 1

        # ── [ASK] branch ──────────────────────────────────────────────────────
        if action_upper.startswith("[ASK]"):
            question = action_text.strip()[5:].strip()  # strip "[ASK]" prefix

            # Query user simulator (async API call)
            answer_text, atomic_count = await self.simulator.answer(
                question=question,
                original_prompt=state.problem.original_prompt,
            )

            new_conversation = state.conversation + [(question, answer_text)]
            new_question_count = state.question_count + atomic_count
            done = turn_count >= self.max_turns

            next_prompt = _build_prompt(state.problem, new_conversation, self.tokenizer)
            next_state = EnvState(
                problem=state.problem,
                conversation=new_conversation,
                turn_count=turn_count,
                question_count=new_question_count,
                done=done,
                prompt=next_prompt,
            )
            return StepResult(
                next_state=next_state,
                reward=0.0,
                cost_q=float(atomic_count),
                cost_t=1.0,
                done=done,
                info={
                    "action_type": "ask",
                    "question": question,
                    "answer": answer_text,
                    "atomic_count": atomic_count,
                },
            )

        # ── [ANSWER] branch ───────────────────────────────────────────────────
        elif action_upper.startswith("[ANSWER]"):
            code = extract_code(action_text)
            context = _extract_helper_context(
                state.problem.degraded_prompt, state.problem.entry_point
            )
            pass_rate = self.executor.run(
                code=code,
                test_cases=state.problem.test_cases,
                entry_point=state.problem.entry_point,
                context=context,
            )

            # Efficiency bonus: small reward for using fewer turns / questions
            turn_bonus = self.efficiency_alpha * (1 - turn_count / self.max_turns)
            q_ratio = state.question_count / max(self.question_budget, 1)
            question_bonus = self.efficiency_beta * max(1 - q_ratio, 0.0)
            reward = pass_rate + turn_bonus + question_bonus

            next_state = EnvState(
                problem=state.problem,
                conversation=state.conversation,
                turn_count=turn_count,
                question_count=state.question_count,
                done=True,
                prompt=state.prompt,
            )
            return StepResult(
                next_state=next_state,
                reward=reward,
                cost_q=0.0,
                cost_t=1.0,
                done=True,
                info={
                    "action_type": "answer",
                    "code": code,
                    "pass_rate": pass_rate,
                    "efficiency_bonus": turn_bonus + question_bonus,
                },
            )

        # ── Malformed output ──────────────────────────────────────────────────
        else:
            # Agent produced neither [ASK] nor [ANSWER] — treat as failed episode
            next_state = EnvState(
                problem=state.problem,
                conversation=state.conversation,
                turn_count=turn_count,
                question_count=state.question_count,
                done=True,
                prompt=state.prompt,
            )
            return StepResult(
                next_state=next_state,
                reward=0.0,
                cost_q=0.0,
                cost_t=0.0,
                done=True,
                info={
                    "action_type": "malformed",
                    "raw_action": action_text[:200],
                },
            )
